[tool.bumper]
current_version = "2.1.0"
versioning_type = "semver"

[[tool.bumper.files]]
file = "./pyproject.toml"
search = 'version = "{current_version}"'

[[tool.bumper.files]]
file = "./skyportal/__init__.py"
search = '__version__ = "{current_version}"'
